Rscript --vanilla results/r1.r < test2.dat
Rscript --vanilla results/r2.r < test3.dat
Rscript --vanilla results/r3.r < test3.dat
Rscript --vanilla results/r4.r < test3.dat
Rscript --vanilla results/r5.r < test3.dat
Rscript --vanilla results/r6.r < test3.dat
Rscript --vanilla results/r7.r < test3.dat
Rscript --vanilla results/r8.r < test3.dat
Rscript --vanilla results/r9.r < test3.dat
Rscript --vanilla results/r10.r < test3.dat
Rscript --vanilla results/r11.r < test3.dat
Rscript --vanilla results/r12.r < test3.dat
Rscript --vanilla results/r13.r < test3.dat
Rscript --vanilla results/r14.r < test3.dat
Rscript --vanilla results/r15.r < test3.dat
Rscript --vanilla results/r16.r < test3.dat
Rscript --vanilla results/r17.r < test3.dat
Rscript --vanilla results/r18.r < test3.dat
Rscript --vanilla results/r19.r < test3.dat
Rscript --vanilla results/r20.r < test3.dat
