Rscript --vanilla results/r1.r < test.dat
Rscript --vanilla results/r2.r < test.dat
Rscript --vanilla results/r3.r < test.dat
Rscript --vanilla results/r4.r < test.dat
Rscript --vanilla results/r5.r < test.dat
Rscript --vanilla results/r6.r < test.dat
Rscript --vanilla results/r7.r < test.dat
Rscript --vanilla results/r8.r < test.dat
Rscript --vanilla results/r9.r < test.dat
Rscript --vanilla results/r10.r < test.dat
