#+begin_export latex
\section*{Introduction}
The program \ty{splitSeq} takes as input a set of sequences and splits
them in fragments of a given length. For example, Figure~\ref{fig:ss}A
shows the input sequence \ty{CGCACAACGA}, and Figure~\ref{fig:ss}B its
split into fragments of length 3. Each fragment is a FASTA sequence
where the header consists of the header of the input sequence
followed by the interval. Notice that the last fragment consists of
the remainder after all full-length fragments have been printed, a
single nucleotide in our example. This imitates the behavior of the
Unix utility \ty{split}.

\begin{figure}
  \begin{center}
    \input{../splitSeq/ss}
  \end{center}
  \caption{Splitting of the sequence \ty{CGCACAACGA} (\textbf{A}) into
    non-overlapping fragments of length 3
    (\textbf{B}), and overlapping fragments of the same length with
    step length 2 (\textbf{C}).}\label{fig:ss}
\end{figure}

By default the fragments generated by \ty{splitSeq} don't overlap, but
the user can set a step length between fragments, which can take any
value greater than zero. If the step length is less than the fragment
length, the output from \ty{splitSeq} can serve as input for sliding
window analyses of the input sequence. For example,
Figure~\ref{fig:ss}C shows the output of \ty{splitSeq} with step
length 2 and fragment length again 3. The fragments now overlap by one
residue.


If after stepping the remaining fragment is shorter than the specified
fragment length, that shorter fragment is returned as the last
fragment for the given sequence. This imitates the behavior of the
Unix utility \ty{split}.

Our outline of \ty{splitSeq} has hooks for imports, functions, and the
logic of the main function.
#+end_export
#+begin_src go <<splitSeq.go>>=
  package main

  import (
	  //<<Imports, Ch. \ref{ch:ss}>>
  )
  //<<Functions, Ch. \ref{ch:ss}>>
  func main() {
	  //<<Main function, Ch. \ref{ch:ss}>>
  }
#+end_src
#+begin_export latex
In the main function we prepare the logging, set the usage, declare
the options, parse the options, and parse the input.
#+end_export
#+begin_src go <<Main function, Ch. \ref{ch:ss}>>=
  util.PrepLog("splitSeq")
  //<<Set usage, Ch. \ref{ch:ss}>>
  //<<Declare options, Ch. \ref{ch:ss}>>
  //<<Parse options, Ch. \ref{ch:ss}>>
  //<<Parse input, Ch. \ref{ch:ss}>>
#+end_src
#+begin_export latex
The usage consists of three parts, the actual usage message, an
explanation of the purpose of \ty{splitSeq}, and an example command.
#+end_export
#+begin_src go <<Set usage, Ch. \ref{ch:ss}>>=
  u := "splitSeq [-h] [options] [files]"
  p := "Split sequences into fragments."
  e := "splitSeq -l 300 -s 30 eco.fasta"
  clio.Usage(u, p, e)
#+end_src
#+begin_export latex
We import \ty{clio}.
#+end_export
#+begin_src go <<Imports, Ch. \ref{ch:ss}>>=
  "github.com/evolbioinf/clio"
#+end_src
#+begin_export latex
Apart from the obligatory version, we set two options, fragment
length, \ty{-l}, and step length, \ty{-s}.
#+end_export
#+begin_src go <<Declare options, Ch. \ref{ch:ss}>>=
  optV := flag.Bool("v", false, "version")
  optL := flag.Int("l", 1000, "fragment length")
  optS := flag.Int("s", 0, "step length (default -l)")
#+end_src
#+begin_export latex
We import \ty{flag}.
#+end_export
#+begin_src go <<Imports, Ch. \ref{ch:ss}>>=
  "flag"
#+end_src
#+begin_export latex
We parse the options and respond to a request for the version. We also
respond to the fragment length and the step length.
#+end_export
#+begin_src go <<Parse options, Ch. \ref{ch:ss}>>=
  flag.Parse()
  //<<Respond to \ty{-v}>>
  //<<Respond to \ty{-l}>>
  //<<Respond to \ty{-s}>>
#+end_src
#+begin_export latex
If the user requested the version, we print the program info, which
contains the version.
#+end_export
#+begin_src go <<Respond to \ty{-v}>>=
  if *optV {
	  util.PrintInfo("splitSeq")
  }
#+end_src
#+begin_export latex
We import \ty{util}.
#+end_export
#+begin_src go <<Imports, Ch. \ref{ch:ss}>>=
  "github.com/evolbioinf/biobox/util"
#+end_src
#+begin_export latex
If the user entered a fragment length less than 1, something is wrong
and we exit with a friendly message.
#+end_export
#+begin_src go <<Respond to \ty{-l}>>=
  if *optL < 1 {
	  log.Fatal("please use fragment length > 0")
  }
#+end_src
#+begin_export latex
We import \ty{log}.
#+end_export
#+begin_src go <<Imports, Ch. \ref{ch:ss}>>=
  "log"
#+end_src
#+begin_export latex
If the user didn't set the step length, we set it to the fragment
length. If the user set the step length to less than 1, again
something must be wrong and we exit with a friendly message.
#+end_export
#+begin_src go <<Respond to \ty{-s}>>=
  if *optS == 0 {
	  (*optS) = *optL
  } else if *optS < 1 {
	  log.Fatal("please use step length > 0")
  }
#+end_src
#+begin_export latex
The remaining tokens on the command line are interpreted as input
files. Their names are passed to \ty{ParseFiles}, which applies the
function \ty{parse} to each one. The function \ty{parse}, in turn,
takes as arguments the fragment length and the step length.
#+end_export
#+begin_src go <<Parse input, Ch. \ref{ch:ss}>>=
  files := flag.Args()
  clio.ParseFiles(files, parse, optL, optS)
#+end_src
#+begin_export latex
Inside parse we retrieve the two arguments we just passed, and
iterate over the sequences in the current file. For each sequence we
store the header and sequence data before we split it into fragments
of the required length.
#+end_export
#+begin_src go <<Functions, Ch. \ref{ch:ss}>>=
  func parse(r io.Reader, args ...interface{}) {
	  //<<Retrieve arguments, Ch. \ref{ch:ss}>>
	  sc := fasta.NewScanner(r)
	  for sc.ScanSequence() {
		  seq := sc.Sequence()
		  header := seq.Header()
		  data := seq.Data()
		  //<<Split sequence, Ch. \ref{ch:ss}>>
	  }
  }
#+end_src
#+begin_export latex
We import \ty{io} and \ty{fasta}.
#+end_export
#+begin_src go <<Imports, Ch. \ref{ch:ss}>>=
  "io"
#+end_src
#+begin_src go <<Imports, Ch. \ref{ch:ss}>>=
  "github.com/evolbioinf/fasta"
#+end_src
#+begin_export latex
We retrieve the two arguments, fragment length and step length.
#+end_export
#+begin_src go <<Retrieve arguments, Ch. \ref{ch:ss}>>=
  optL := args[0].(*int)
  optS := args[1].(*int)
#+end_src
#+begin_export latex
To split the sequence, we loop over the fragment starting positions
and print each corresponding fragment. After the loop we print the
last fragment.
#+end_export
#+begin_src go <<Split sequence, Ch. \ref{ch:ss}>>=
  n := len(seq.Data())
  m := n - *optL
  s := 0
  for ; s < m; s += *optS {
	  //<<Print fragment, Ch. \ref{ch:ss}>>
  }
  //<<Print last fragment, Ch. \ref{ch:ss}>>
#+end_src
#+begin_export latex
To print a fragment, we get its header and sequence, construct a new
sequence from them, and print it. As illustrated in
Figures~\ref{fig:ss}B and C, the new header consists of the old header
with start and end coordinates appended.
#+end_export
#+begin_src go <<Print fragment, Ch. \ref{ch:ss}>>=
  e := s + *optL
  h := header + "|"
  h += strconv.Itoa(s+1) +
	  ".." +
	  strconv.Itoa(e)
  d := data[s:e]
  ns := fasta.NewSequence(h, d)
  fmt.Println(ns)
#+end_src
#+begin_export latex
We import \ty{strconv} and \ty{strconv}.
#+end_export
#+begin_src go <<Imports, Ch. \ref{ch:ss}>>=
  "strconv"
  "fmt"
#+end_src
#+begin_export latex
The last fragment extends to the end of the sequence. We print it,
unless it is empty.
#+end_export
#+begin_src go <<Print last fragment, Ch. \ref{ch:ss}>>=
  e := n
  if s < e {
	  h := header + "|"
	  h += strconv.Itoa(s+1) +
		  ".." +
		  strconv.Itoa(e)
	  d := data[s:e]
	  ns := fasta.NewSequence(h, d)
	  fmt.Println(ns)
  }
#+end_src
#+begin_export latex
We are done writing \ty{splitSeq}, so we test it.

\section*{Testing}
The outline of our testing code has hooks for imports and the testing
logic.
#+end_export
#+begin_src go <<splitSeq_test.go>>=
  package main

  import (
	  "testing"
	  //<<Testing imports, Ch. \ref{ch:ss}>>
  )
  func TestSplitSeq(t *testing.T) {
	  //<<Testing, Ch. \ref{ch:ss}>>
  }
#+end_src
#+begin_export latex
We construct a set of tests and run each one.
#+end_export
#+begin_src go <<Testing, Ch. \ref{ch:ss}>>=
  var tests []*exec.Cmd
  //<<Construct tests, Ch. \ref{ch:ss}>>
  for i, test := range tests {
	  //<<Run test, Ch. \ref{ch:ss}>>
  }
#+end_src
#+begin_export latex
We import \ty{exec}.
#+end_export
#+begin_src go <<Testing imports, Ch. \ref{ch:ss}>>=
  "os/exec"
#+end_src
#+begin_export latex
There are two constant aspects of our tests, the 10\,bp input
sequence, which is shown in Figure~\ref{fig:ss} and is stored in file
\ty{test.fasta}, and the program \ty{splitSeq}. We set these constant
parts of our tests to convenient variables. Then we construct a test
without options, a test of the fragment length, \ty{-l}, and a test of
the step size, \ty{-s}.
#+end_export
#+begin_src go <<Construct tests, Ch. \ref{ch:ss}>>=
  f := "test.fasta"
  p := "./splitSeq"
  //<<Test without options, Ch. \ref{ch:ss}>>
  //<<Test \ty{-l}, Ch. \ref{ch:ss}>>
  //<<Test \ty{-s}, Ch. \ref{ch:ss}>>
#+end_src
#+begin_export latex
We construct a test without options and store it.
#+end_export
#+begin_src go <<Test without options, Ch. \ref{ch:ss}>>=
  test := exec.Command(p, f)
  tests = append(tests, test)
#+end_src
#+begin_export latex
We test with fragment length 3.
#+end_export
#+begin_src go <<Test \ty{-l}, Ch. \ref{ch:ss}>>=
  test = exec.Command(p, "-l", "3", f)
  tests = append(tests, test)
#+end_src
#+begin_export latex
Recall that our default fragment length is 1000 while our testing
sequence consists only of 10 residues. To see the step length in
action, we therefore keep the fragment length of 3 from the previous
test \emph{and} set the step length to 2.
#+end_export
#+begin_src go <<Test \ty{-s}, Ch. \ref{ch:ss}>>=
  test = exec.Command(p, "-l", "3", "-s", "2", f)
  tests = append(tests, test)
#+end_src
#+begin_export latex
When running a test, we compare the results we get and the results we
want, which are kept in files \ty{r1.txt}, \ty{r2.txt}, and
\ty{r3.txt}.
#+end_export
#+begin_src go <<Run test, Ch. \ref{ch:ss}>>=
  g, err := test.Output()
  if err != nil {
	  t.Error(err)
  }
  f := "r" + strconv.Itoa(i+1) + ".txt" 
  w, err := os.ReadFile(f)
  if err != nil {
	  t.Error(err)
  }
  if !bytes.Equal(g, w) {
	  t.Errorf("%s - get:\n%s\nwant:\n%s\n", f, g, w)
  }
#+end_src
#+begin_export latex
We import \ty{strconv}, \ty{os}, and \ty{bytes}.
#+end_export
#+begin_src go <<Testing imports, Ch. \ref{ch:ss}>>=
  "strconv"
  "os"
  "bytes"
#+end_src
